#!/bin/bash

usage_string="usage: ./dev/$(basename "$0") [-a][-s][-m]

 Options:
  -a, --annotate	Make an unsigned, annotated tag object
  -s, --sign            Make a GPG-signed tag, using the default
  			e-mail address's key
  -m, --message	        Use the provided tag message (instead of
  			prompting)
  -h, --help            Display this help message and exit
"

usage() { echo -n "$usage_string" 1>&2; }

declare -A help_opts=(
	[-h]=1 [--help]=1)

tag_opt=""
message_opt=""
sign_opt=""

if [[ $# = 1 && "${help_opts[$1]}" ]]; then
	usage
	exit 0
fi

for arg in $@
do
        case $arg in
                -a=*|--annotate=*)
                        TAG="${arg#*=}"
			tag_opt="-a $TAG"
                        shift
                        ;;
		-m=*|--message=*)
			MESSAGE="${arg#*=}"
			message_opt="-m $MESSAGE"
			shift
			;;
		-s*|--sign*)
			sign_opt="--sign"
			shift
			;;
                *)
                        # unknown option
                        ;;
        esac
done

git $tag_opt $message_opt $sign_opt
git push origin $TAG 

exit 0
